Fix Visual Studio 2017 wrong error C2397
When using the list-initialization, Visual Studio 2017 reports wrong error "C2397: Element '2': conversion from 'const int' to 'const unsigned __int64' requires a narrowing conversion"